users/sivanov/README.md
всякое бывает, дайте аппрув пожалуйста
=> добавил файл README

users/aominakov/README.md
=> ura ura ya koder

users/sivanov/TDD_lesson.ipynb
файл ноутбука с сегодняшнего урока по TDD
=> tdd lesson code added

users/aominakov/homework_git.ipynb
=> just create file

.gitignore
Добавил корневой .gitignore - файл, чтобы git не реагировал на папки .ipynb_checkpoints и файлы *.pyc
=> added .gitignore to root folder

users/sivanov/Lesson_7_commands.ipynb, users/sivanov/batchtestcall.py, users/sivanov/lesson_1_work_1_v2_TDD_in_progress.ipynb, users/sivanov/timsort/random_things.ipynb
=> added lesson 7 homework

users/mvandreeva/lesson_9_HW_objects_to_files/.ipynb_checkpoints/lesson_9_HW_objects_to_files-checkpoint.ipynb, users/mvandreeva/lesson_9_HW_objects_to_files/file.txt, users/mvandreeva/lesson_9_HW_objects_to_files/lesson_9_HW_objects_to_files.ipynb
ДЗ сделать функцию чтения объекта из файла
=> Added lesson_9_HW_objects_to_files

users/amtsurkov/lesson_14/1.txt, users/amtsurkov/lesson_14/1_v2.txt, users/amtsurkov/lesson_14/2.txt, users/amtsurkov/lesson_14/delo.py, users/amtsurkov/lesson_14/lesson_14.ipynb, users/amtsurkov/lesson_14/lesson_14_2.ipynb, users/amtsurkov/lesson_14/spisok_dela.py
Добавил нотебучек и модули из 14 занятия
=> Amtsur lesson 14

users/aominakov/lesson16_minakovgit.ipynb
=> minakov_lesson16

users/aochernyshev/price_checker/config.py, users/aochernyshev/price_checker/mailer.py, users/aochernyshev/price_checker/main.py, users/aochernyshev/price_checker/parsers/chitai_gorod_parser.py, users/aochernyshev/price_checker/product.py
=> added price_checker

users/mvandreeva/lesson_14_HW_Modules_classes/Data_write.ipynb, users/mvandreeva/lesson_14_HW_Modules_classes/deal_list__test.ipynb, users/mvandreeva/lesson_14_HW_Modules_classes/deals.py
Добавила ДЗ к 14 уроку (первая половина про список дел). Запись в файл и чтение - через методы.
Есть вопрос: реализовала одним методом (display_done_as_planned) вывода дел, сделанных в тот же день в который их запланировали и вывод индексов этих дел, но для индекса нужно передать значение в метод (хотелось бы использовать True, но срабатывает и когда передаешь просто число. Как лучше реализовать?
=> added lesson_14_HW

users/sivanov/lessons/lesson_16_hw/lesson_16_hw.ipynb, users/sivanov/lessons/lesson_16_hw/mailstuff/basemail.py, users/sivanov/lessons/lesson_16_hw/mailstuff/getdatafrom.py, users/sivanov/lessons/lesson_16_hw/mailstuff/mailto.py
домашка к 16 уроку, по отправке почты и парсингу сайтов
цену добывает
почту отправляет.
вопросики остались.
=> hw for lesson 16 (mailing and site parsing)

users/amtsurkov/lesson_22/dags/TrialSportPageProcessing.py, users/amtsurkov/lesson_22/dags/dag_trialsport_5_items.py
Надеюсь все уже успели набить шишки и поразбираться в коде.
Так что теперь взгляните на код когда он снабжен комментариями. Правда стало удобнее читать и понимать?
=> add comment

users/mvandreeva/lesson_15_HW_web_prices/lesson_15_HW_web_prices.ipynb, users/mvandreeva/lesson_15_HW_web_prices/test_web_check.ipynb, users/mvandreeva/lesson_15_HW_web_prices/web_check.py, users/mvandreeva/lesson_23_HW_mypy_black_pylint/changes_mypy_black.diff, users/mvandreeva/lesson_23_HW_mypy_black_pylint/web_check_v2.py
Проверила свой старый модуль через mypy и black, изменения загрузила в отдельный файл, т.к. забыла закоммитить после mypy. К сожалению, нормально оформленных тестов нет, работоспособность не проверяла пока.
git писал, что изменилась версия python в файлах к уроку 15, потому обновила и эти файлы.
=> mypy and black changes. And python3 update for version on lesson-15

users/ADKazdym/a1.txt
=> change dir

users/alzharin/homework_1.ipynb
=> first_HW_alzharin

users/alzharin/homework_2.ipynb
=> second_HW_alzharin

users/andreev-aleksey/lesson_03/git_base.ipynb
=> add git_base to lesson_03

users/asneyman/a1.txt
not understend how i can do this soso!
=> save dir content

users/jatashpulatov/folder/a1.txt
Создание тестовой ветки и внедрение файла
=> Home work 2 jatashpulatov

users/jatashpulatov/lesson_04/hw_04.ipynb
Домашнее задание №4, часть 1 - оценка времени реализации функций.
Вопрос по гиту:
- файл у меня находится не прям в проектной папке users/jatashpulatov, а внутри папки lesson_04, которая в проектной. Я добавляю целую папку lesson_04. В итоге в ветке моя папка становится jatashpulatov/lesson_04. Правильно ли это, Если нет, направьте на путь истинный) Благодарю
=> estimate time of hw04

users/andreev-alexander/lesson_06/HW_06.py, users/andreev-alexander/lesson_07/HW_07.py, users/andreev-alexander/lesson_07/test_HW_07.py
Реализован класс `Phonebook` с методами:
- `add_new_record`
- `sort_phonebook_by_name`
- `search_by_name`
- `search_by_city`
- `person_list`
Реализованы тесты для этого класса.
=> Hw 07 andreev alexander

library/theory/python_basics_5.ipynb, users/AMTsurkov/home_work_1/home_work_1.ipynb
=> lesson sql v2

.gitignore, users/andreev-alexander/lesson_05/hw_exclusion.py, users/andreev-alexander/lesson_05/test_calc_all.py, users/andreev-alexander/lesson_05/test_calc_plus_minus.py, users/andreev-alexander/lesson_05/test_phone_book_func.py, users/andreev-alexander/lesson_05/test_safe_divide.py
=> Hw 05 andreev alexander

src/simple_model_project/andreev_alexander_some_module.py, src/simple_model_project/andreev_alexander_some_module_test.py
Домашнее задание: реализация абстрактного класса
=> Реализация абстрактного класса

src/simple_model_project/EANabatov_module.py, src/simple_model_project/EANabatov_test.py
Реализация домашнего задания
1. Наследование от родительского класса
2. Реализация паттерна синглтон в задании
3. Написание тестов на проверку функционала класса
4. Проверка модулей с использованием black и mypy
=> Домашнее задание от SIvanov

src/simple_model_project/EANabatov_module.py, src/simple_model_project/EANabatov_test.py
исправил ошибки с урока
прошел mypy и black
=> Исправление косяков прошлого пула

users/andreev-alexander/parser/async_sup_parser.py, users/andreev-alexander/parser/sup_parser.py
Парсинг сайта http://101arenda.ru/.
Результат выводится в консоле принтом в виде словаря.
=> Парсер самого лучшего сайта :)

users/andreev-aleksey/parser_lenta/lenta.py
Парсер получает:
- список товаров из каталога https://lenta.com/catalog/
- список товаров **только с первой страницы**
Вывод результата идет через print().
```python
[{   'category_name': 'Название категории',
'link': 'ссылка на категорию'}]
'info': [   {  'goods_name': 'название товара',
'first_price': 'обычная цена',
'second_price': 'цена по карте'
}]
}]
```
=> Парсер каталога товаров Ленты

users/mvandreeva/project_equilibrium/developers/capital_group_cap_towers/cap_towers_parsing.py, users/mvandreeva/project_equilibrium/developers/capital_group_cap_towers/sources/capitaltowers, users/mvandreeva/project_equilibrium/developers/capital_group_cap_towers/test_cap_towers_parsing.py
На официальном сайте проекта Capital Towers отсутствует информация о цене.
Сохраню наработки, возможно вернемся позже
=> MVAndreeva started parsing the Capital Towers, but there is no price

users/andreev-alexander/lesson_08/HW_08.py
Для второго задания использовал классы `Phonebook` и `PhonebookRecord` из прошлого домашнего задания #120
=> HW_08. Работа с файлами txt и pickle

users/andreev-alexander/lesson_10/HW_10.py, users/andreev-alexander/lesson_10/create_db.py
- Создание и наполнение БД взял у коллеги, источник указал (слишком хорошо, чтобы писать это самому)
- Два запрос из ДЗ
=> HW_10 Первая работа с SQL

users/andreev-alexander/lesson_09/HW_09.py, users/andreev-alexander/lesson_09/test_HW_09.py
Домашняя работа сделана на базе ранее реализованных классов.
- Добавил в `PhonebookRecord` и `Phonebook` работу со списком хобби и возрастом
- Добавил три отдельных функции для сохранения в файл pickle, извлечения данных из него и фильтр по возрасту
- Добавил несколько тестов под новый метод в классе `search_by_hobby()`
Оставил принты, чтобы можно было запустить файл и посмотреть результат.
=> HW_09. Добавление в телефонную книгу хобби и возраста

users/sivanov/lessons/lesson_33_working_with_classes/working_with_classes.ipynb
Ноутбук с занятия про UltraStripper
=> Sivanov working with classes

src/simple_model_project/abstractmodule.py
в интерфейс модуля добавлен метод get_state(), возвращающая состояние 
метод step() теперь не возвращает никаких значений.
=> обновление интерфейса модулей

src/simple_model_project/eanabatov_module.py, src/simple_model_project/eanabatov_py_log.log, src/simple_model_project/eanabatov_test.py
Доработанный модуль под обновления интерфейса модуля @isergy 
_mypy + pylint + black_
=> EANabatov_Model_v2

users/tttest/README
=> Lecture2tttest

users/rnyunusov/README
=> add folder rnyunusov

users/dptimofeev/readme
added some info about me and my folder
=> attempt #2

library/exercises/hw-1/theory_console_command.ipynb
собственно, сабж
добавил в /library/exercises/hw-1/theory_console_command.ipynb
=> добавил ipynb с первого занятия

users/oekorchevaya/README.md
=> oekorchevaya-hw2-part1

library/streams/2024/hw_status, library/streams/2024/visits_status
=> Заполнил свои данные в файлах

library/streams/2024/hw_status, library/streams/2024/visits_status
Информация о посещении лекции и выполненном дз
=> Aomargolina hw and visits info

users/rstarasov/exercise/hw-3/hw-3-part-2.ipynb
Создал файл (ноутбук) в своей директории с ДЗ по Python, выполнил все задачи и операции
=> rstarasov ДЗ №3 (часть 2)(первый ноутбук с командами python)

library/streams/2024/hw_status, library/streams/2024/visits_status
=> Status on 07/02

users/aaarisova/exercise/hw-3/hw-3-part-2/hw3-p2.ipynb
=> Arisova hw3 part2

users/avlotsmanov/exercise/hw4/hw-4_lotsmanov.ipynb
=> avlotsmanov-hw4-python-list

users/rstarasov/exercise/hw-4/hw-4.ipynb
Создал файл hw-4 в своей директории и выполнил там последнюю домашку
=> 4-ая домашка

users/vvbykov/exercise/hw4/hw-4.ipynb
=> HW-4 is done

library/streams/2024/hw_status
=> The work status has been updated

users/oekorchevaya/exercise/hw-5/hw-5_clear.ipynb
Для любителей красивых ноутбуков оформила все части 5 домашки в один ноутбук. При желании можно располовинить
=> Добавила все части домашки в юпитер ноутбук с заголовками))

users/ismatrosova/exercise/hw4/hw-4.ipynb
=> ismatrosova-hw4-start сделала д4

library/exercises/hw-5/hw-5.ipynb
практически те же самые задания, что и в файлах hw-5-part-1.txt  hw-5-part-2.txt  hw-5-part-3.txt  hw-5-part-4.txt  hw-5-part-5.txt, с небольшими комментариями и в одном файле, который можно скопировать и прямо в нем делать. Огромное спасибо @okorch за проделанную работу )
=> добавил задания по hw-5 в виде юпитер ноутбука

users/avmorozova/exercise/hw4/hw4.ipynb
с последним стихом,так и не поняла,что должно было получиться)но вроде все правильно написала
=> avmorozova_hw4

users/mvandreeva/study2024/exercise/hw4/hw-4.ipynb
=> MVAndreeva hw4

users/mvandreeva/study2024/exercise/hw5/hw-5.ipynb
Домашнее задание по 5му уроку
Пока залью первые 4 части.
Остальное (5 часть) на этом потоке пока не проходили 
и объем там большой - добавлю в отдельный ПР
=> Mvandreeva hw5 parts 1-4

users/aaarisova/exercise/hw-5/hw-5-part-1.ipynb, users/aaarisova/exercise/hw-5/hw-5-part-2.ipynb, users/aaarisova/exercise/hw-5/hw-5-part-3.ipynb, users/aaarisova/exercise/hw-5/hw-5-part-4.ipynb
=> Arisova hw 5.4

users/aaarisova/exercise/hw-5/hw-5-part-1.ipynb, users/aaarisova/exercise/hw-5/hw-5-part-2.ipynb, users/aaarisova/exercise/hw-5/hw-5-part-3.ipynb
=> Первая часть д/з 5

users/oekorchevaya/exercise/hw-5/hw-5.ipynb
Осталось написать немного функций. Доделывать буду в этой ветке, но уже жду комментарии и замечания
=> okorch HW5

library/streams/2024/hw_status, library/streams/2024/visits_status
Обновила статусы по домашке/ посещениям
=> MVAndreeva visit-status update

library/streams/2024/hw_status, library/streams/2024/visits_status
=> Status update

library/streams/2024/hw_status, library/streams/2024/visits_status
Обновил инфу по выполнению ДЗ и посещению лекций.
В посещение добавил дату 14.02.24
=> JATashpulatov - Update hw_status and visits_status

users/vvbykov/exercise/hw5/hw-5.ipynb
=> HW5 branch

library/streams/2024/hw_status, library/streams/2024/visits_status
=> saivanov обновил hw_status и visits_status

users/rstarasov/exercise/hw-5/hw-5-5.ipynb
=> Сделал hw-5-5

library/streams/2024/hw_status, library/streams/2024/visits_status
Дополнил данные о выполнении ДЗ и посещаемости
=> rstarasov дополнил данные о выполнении ДЗ и посещаемости

users/vstarasova/exercise/hw4/hw-4.ipynb, users/vstarasova/exercise/hw5/hw-5.ipynb
ДЗ 5 полностью.
Решение одной из задач (где-то в начале) полностью закоммичено, потому что оно выдает ошибку (но я так поняла по заданию что так и должно быть).
ДЗ было сделано на 90% еще 2 недели назад, никак не могла добить последние пару задачек
=> Vstarasova hw5

library/streams/2024/hw_status, library/streams/2024/visits_status
=> Update hw_status & visits_status

users/vvbykov/exercise/hw7/hw-7-part-1.ipynb, users/vvbykov/exercise/hw7/hw-7-part-2.ipynb, users/vvbykov/exercise/hw7/hw-7-part-check-yourself.ipynb
The home assignment #7 has been done.
=> VVBykov HW-7 

library/streams/2024/hw_status, library/streams/2024/visits_status
=> aemareev update visits_status & hw_status

users/aemareev/exercise/hw9/functions_hw5.py, users/aemareev/exercise/hw9/functions_hw7.py, users/aemareev/exercise/hw9/test_functions_hw5.py, users/aemareev/exercise/hw9/test_functions_hw7.py
=> aemareev-hw9-tests

users/rstarasov/exercise/hw-7/hw-7-part-2-new.ipynb, users/rstarasov/exercise/hw-7/hw-7-part-check-yourself-new.ipynb
Сделал второе и третье задание hw-7
=> rstarasov hw-7-part-2

library/streams/2024/groups
=> Update groups 3

library/working_time/wt240331.py
Добавил код всех участников с КодиЭдитора (24.03.31, вск, 9:00 - 11:10)
=> Add file wt240331.py (practice in CodeEditor)

library/streams/2024/groups, library/streams/2024/hw_status, library/streams/2024/visits_status
Добавила информацию в файл group, обновила статусы дз и посещения лекций
=> MVAndreeva update group and hw/visit status

library/streams/2024/groups, library/streams/2024/hw_status, library/streams/2024/visits_status
добавил инфо о готовности ДЗ, посещаемости и указал свою группу
=> rstarasov добавил инфо о готовности ДЗ, посещаемости и указал свою группу

users/vstarasova/exercise/hw8/HW-8.ipynb
ДЗ 8.
Выкладываю версию без теста на ввод  ['1','1','1']. Когда разберемся с этой проблемой - можно добавить.
Как звучит проблема.
> функция делает проверку: 
> triangle_exist = (a < (b + c)) and (b < (a + c)) and (c < (a + b))
> 
> если проходить эту функцию с данными ['4','6','6'] то это условие равно False
> Если подать ['1','1','1'] то условие равно True.
> 
> Вопрос:
> 
> как это питон так волшебно складывает строки, что выражение
> 1 < 11 and  1 < 11 and 1 < 11 
> у него почему-то True, а
> 
> 4 < 66 and 6 <46 and 6 < 46
> это False?
Далее.
Тестов у меня немного. 
Идею общей функции, вызывающей все тесты, и считающей количество пройденных и непройденных, придумала сама. Варианты реализации подсматривала, поскольку не знала, что можно функции сделать элементами списка, и вызвать по …
=> tarasovavs HW-8

users/vstarasova/exercise/hw7/hw-7-part-1.ipynb, users/vstarasova/exercise/hw7/hw-7-part-2.ipynb, users/vstarasova/exercise/hw7/hw-7-part-check-yourself.ipynb
ДЗ 7, все 3 части.
По 3 части: все задачки с тегом #1 кроме трех с тегом #2.
=> HW 7 vstarasova (3 parts)

users/aomargolina/exercice/hw5/hw-5/hw-5-part-1_3.ipynb
=> HW5 part 1-3

users/aomargolina/exercice/hw4/hw4.ipynb
=> Aomargolina hw4

library/streams/2024/hw_status, library/streams/2024/visits_status
=> JATashpulatov - Update hw_status & visits_status

library/working_time/class_240403.py
=> Файл с онлайн кодингом с занятия 240403

users/aomargolina/exercice/purcase/Purcase_and_total_price.ipynb
Создание функции для записи трат и функции для подсчета общей суммы трат
и тесты к ним
=> Aomargolina purcase

users/rnyunusov/exercise/hw8/hw8.ipynb
=> rnyunusov-hw8

users/SAMaltsev/SAMaltsev2024/exercise/hw-3/hw-3-2.ipynb
Сделал вторую часть ДЗ №3, возникла ошибка при проверке результата вычисления обеих решений дискриминанта, позже возможно вернусь к нему, но пока проделана отличная работа
1 часть на зубрежку и прохождение собеседования делать смысла нет, пока не догоню вас
=> сделал дз№3 (часть2)

users/aemareev/exercise/hw12/bank_account.py, users/aemareev/exercise/hw12/book.py, users/aemareev/exercise/hw12/car.py, users/aemareev/exercise/hw12/circle.py, users/aemareev/exercise/hw12/date.py, users/aemareev/exercise/hw12/education_institution.py, users/aemareev/exercise/hw12/matrix.py, users/aemareev/exercise/hw12/point.py, users/aemareev/exercise/hw12/polygon.py, users/aemareev/exercise/hw12/shape.py, users/aemareev/exercise/hw12/shopping_cart.py, users/aemareev/exercise/hw12/student.py, users/aemareev/exercise/hw12/triangle.py, users/aemareev/exercise/hw12/warehouse.py
немного тестов есть в каждом модуле, в отдельные модули тесты пока не выносил
=> aemareev-hw12-oop

users/aaarisova/exercise/hw-12/matrix.py, users/aaarisova/exercise/hw-12/test_matrix.py, users/aaarisova/exercise/hw-12/test_warehouse.py, users/aaarisova/exercise/hw-12/warehouse.py
Добавила класс Склад. Сделала класс Матрицы + тесты
=> Arisova_HW-12-p3   Warehouse + Matrix

users/kaanikin/exercise/hw-14/task-1-complexity.ipynb, users/kaanikin/exercise/hw-14/task-2-list-sort.ipynb
=> Kaanikin hw14

users/aomargolina/exercice/15_05_24_Library.ipynb, users/aomargolina/exercice/15_05_24_Library.py, users/aomargolina/exercice/library/15_05_24_Library.ipynb, users/aomargolina/exercice/library/Library.ipynb
код с Занятия 15 мая
дописали класс Library
и написали класс User
=> Library 15 05 24

library/theory/ipython-sql-example.ipynb
короткий пример как попроще работать с БД в Юпитер-блокнотах. 
Если придумаю как ещё проще - напишу)
=> добавил пример использования ipython-sql в jupyter notebook

users/aomargolina/exercice/hw11/hw11.ipynb
=> часть 11 задания

library/streams/2024/team.html
Закинул ссылку на страничку в общий файл
=> rstarasov update team.html

library/streams/2024/team.html
изменение в файле команды - добавление ссылки
=> изменение в файле команды - добавление ссылки

users/aomargolina/exercice/library/15_05_24_Library.ipynb, users/aomargolina/exercice/library/Library.ipynb
создание класса Book и Library
тесты на общее кол-во книг в библиотеке и среднее кол-во страниц
=> создание класса Book и Library, тестов к их методам

library/projects/Price_bot/bot/bot.py, library/projects/Price_bot/bot/parser_for_bot.py
Добавил рабочий парсер. Немного переделал функцию взаимодействия с парсером в самом боте
=> rstarsov price_bot

library/projects/teleban/src_rbc_ru/rbc_parser.py
Парсер для rbc.ru с:
классом
проверкой дублирования ссылок и дописыванием тегов
выводом в SQL
=> Вроде, чёто получилось)

library/projects/teleban/src_auto/handlers.py, library/projects/teleban/src_auto/keyboards.py, library/projects/teleban/src_auto/parser.py, library/projects/teleban/src_auto/text_data.py, library/projects/teleban/src_rbc_ru/handlers.py, library/projects/teleban/src_rbc_ru/keyboards.py, library/projects/teleban/src_rbc_ru/text_data.py
Добавил Авто.ру и, вроде, ничего не сломал)
=> Добавил Авто.ру

.github/workflows/teleban_deployment.yml, library/projects/teleban/src_kinopoisk_ru/parser.py, library/projects/teleban/teleban_deployment.yml
=> teleban deploy test
